-- AlterTable
ALTER TABLE "UserLoginData" ADD COLUMN     "AccountActivated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "RenewalCount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "CreatedAt" DROP NOT NULL,
ALTER COLUMN "CreatedAt" DROP DEFAULT,
ALTER COLUMN "RenewedAt" DROP NOT NULL,
ALTER COLUMN "RenewedAt" DROP DEFAULT;
